image: nixos/unstable
packages:
  - nixos.nixUnstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  site: misterio.me
oauth: pages.sr.ht/PAGES:RW
tasks:
- build: |
    cd $site
    nix --quiet build
- package: |
    tar -C $site/result/public -cvz . > site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
