image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
packages:
  - nixos.nixUnstable
environment:
  site: misterio.me
tasks:
- package: |
    cd $site
    nix --experimental-features "nix-command flakes" build
    tar -C result -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
