image: nixos/unstable

packages:
  - nixos.cachix

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  site: misterio.me

oauth: pages.sr.ht/PAGES:RW

secrets:
  - f2907d38-97b4-4e7d-9fb9-57b3fb0135af

tasks:
- setup_cachix: |
    cat ~/.cachix_token | cachix authtoken --stdin
    cachix use misterio
- build: |
    cd misterio.me
    cachix watch-exec misterio nix build
- package: |
    time tar -C misterio.me/result/public -cvz . > site.tar.gz
- upload: |
    time acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
    time acurl -f https://pages.sr.ht/publish/$site -Fprotocol=GEMINI -Fcontent=@site.tar.gz
