image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  site: misterio.me
oauth: pages.sr.ht/PAGES:RW
tasks:
- build: |
    cd misterio.me
    nix --quiet build
- package: |
    tar -C misterio.me/result/public -cvz . > site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
    acurl -f https://pages.sr.ht/publish/$site -Fprotocol=GEMINI -Fcontent=@site.tar.gz
