name: "Gabriel Fontes"
description: "My personal website and projects"
domain: "m7.rs"

default_theme: catppuccin

plugins:
  - jekyll-extlinks
  - jekyll-relative-links

extlinks:
  attributes: 
    class: external

relative_links:
  enabled: true
  collections: true

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  # Set HTML layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      gemini: false
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      gemini: false

  # Set gemini layouts
  -
    scope:
      path: "**/*.gmi"
      type: "posts"
    values:
      layout: "post.gmi"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
    values:
      layout: "default.gmi"
      gemini: true

  # Post default metadata
  -
    scope:
      path: ""
    values:
      language: "en"
      author: "Gabriel Fontes"
  # All markdown pages have a gemini version, by default
  -
    scope:
      path: "**/*.md"
    values:
      has_gemini: true
