name: "Gabriel Fontes"
description: "My personal website and projects"
domain: "misterio.me"

plugins:
  - jekyll-last-modified-at

last-modified-at:
  date-format: "%F %z" # ISO 8601


include: [".well-known"]

source: _main

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts
  notes:
    output: true
    permalink: /notes/:path/index:output_ext
    name: Notes

defaults:
  # Set HTML layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      gemini: false
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "note.html"
      gemini: false
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      gemini: false

  # Set gemini layouts
  -
    scope:
      path: "**/*.gmi"
      type: "posts"
    values:
      layout: "post.gmi"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
      type: notes
    values:
      layout: "note.gmi"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
    values:
      layout: "default.gmi"
      gemini: true

  # Post default metadata
  -
    scope:
      path: ""
    values:
      language: "en"
      author: "Gabriel Fontes"
  # All markdown pages have a gemini version, by default
  -
    scope:
      path: "**/*.md"
    values:
      has_gemini: true
