include: [".well-known"]

name: "Gabriel Fontes"
description: "My personal website and projects"
url: "https://misterio.me"

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay

# Permalink dos posts
permalink: /:year/:month/:day/:title:output_ext

collections:
  pages:
    output: true
    permalink: /:path:output_ext

defaults:
  # Set pages layout
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default.html"
      gemini: false
  # Use post layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      gemini: false
  # Set gemini layouts
  -
    scope:
      path: "**/*.gmi"
      type: "pages"
    values:
      layout: "default.gmi"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
      type: "posts"
    values:
      layout: "post.gmi"
      gemini: true
