name: "Gabriel Fontes"
description: "My personal website and projects"
url: "https://misterio.me"

include: [".well-known"]

source: _main

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title:output_ext
    name: Posts

defaults:
  # Set HTML layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      gemini: false
      has_gemini: true
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      gemini: false
      has_gemini: true

  # Set gemini layouts
  -
    scope:
      path: "**/*.gmi"
      type: "posts"
    values:
      layout: "post.gmi"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
    values:
      layout: "default.gmi"
      gemini: true

  # Post default metadata
  -
    scope:
      path: ""
      type: "posts"
    values:
      language: "en"
      author: "Gabriel Fontes"
