name: "Gabriel Fontes"
description: "My personal website and projects"
domain: "m7.rs"

default_theme: catppuccin
themes_url: //colors.m7.rs/themes

plugins:
  - jekyll-extlinks
  - jekyll-relative-links

extlinks:
  attributes: 
    class: external

relative_links:
  enabled: true
  collections: true

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  # Set layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
  -
    scope:
      path: ""
    values:
      layout: "default.html"

  # Default metadata
  -
    scope:
      path: ""
    values:
      language: "en"
      author: "Gabriel Fontes"
