name: "Gabriel Fontes"
description: "My personal website and projects"
domain: "m7.rs"
url: "https://m7.rs/"

dark_scheme: rose-pine-moon
light_scheme: rose-pine-dawn
printing_scheme: standardized-light # Must have #FFFFFF background


plugins:
  - jekyll-target-blank

target-blank:
  add_css_classes: external

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      nav_current: "/blog/"
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      language: "en"
      author: "Gabriel Fontes"
