include: [".well-known"]

name: "Gabriel Fontes"
description: "My personal website and projects"
url: "https://misterio.me"

plugins:
  - liquid-nested-sort

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay

# Permalink dos posts
permalink: /:year/:month/:day/:title:output_ext

collections:
  pages:
    output: true
    permalink: /:path:output_ext

defaults:
  # Set pages layout
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default.html"
      gemini: false
      has_gemini: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      gemini: false
      has_gemini: true

  # Set gemini layouts
  -
    scope:
      path: "**/*.gmi"
      type: "pages"
    values:
      layout: "default.gmi"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
      type: "posts"
    values:
      layout: "post.gmi"
      gemini: true

  # Post default metadata
  -
    scope:
      path: ""
      type: "posts"
    values:
      language: "en"
      author: "Gabriel Fontes"

  # Set disciplinas layout
  -
    scope:
      path: "_pages/disciplinas/*.html"
      type: "pages"
    values:
      layout: "disciplinas.html"
      has_gemini: false
  -
    scope:
      path: "_pages/disciplinas/*.json"
      type: "pages"
    values:
      layout: "disciplinas.json"
      has_gemini: false
