include: [".well-known"]

name: "Gabriel Fontes"
description: "My personal website and projects"
url: "https://misterio.me"

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay

# Permalink dos posts
permalink: /:year/:month/:day/:title:output_ext

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  # Set pages layout
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      gemini: false
  # Use post layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      gemini: false
  # Set gemini layouts
  -
    scope:
      path: "**/*.gmi"
      type: "pages"
    values:
      layout: "default-gemini"
      gemini: true
  -
    scope:
      path: "**/*.gmi"
      type: "posts"
    values:
      layout: "post-gemini"
      gemini: true
