name: "Gabriel Fontes"
description: "My personal website and projects"
domain: "m7.rs"

dark_scheme: tokyo-city-terminal-dark
light_scheme: tokyo-city-terminal-light


plugins:
  - jekyll-extlinks
  - jekyll-relative-links

extlinks:
  attributes: 
    class: external

relative_links:
  enabled: true
  collections: true

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      nav_current: "/blog/"
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      language: "en"
      author: "Gabriel Fontes"
