image: nixos/unstable

packages:
  - nixos.cachix
  - nixos.hut

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"

oauth: pages.sr.ht/PAGES:RW

secrets:
  - f2907d38-97b4-4e7d-9fb9-57b3fb0135af

tasks:
- setup_cachix: |
    cat ~/.cachix_token | cachix authtoken --stdin
    cachix use misterio
- build: |
    cd misterio.me
    cachix watch-exec misterio nix build
